Repository bespoke-silicon-group/bsg_manycore, pull requests merged in 2021-05, with the labels that each got.

#515 Fix nonsynth code in bsg_manycore_link_sif_tieoff
  v/bsg_manycore_link_sif_tieoff.v
Labels: bug

#492 Adding bsg_manycore_endpoint_fc
  machines/arch_filelist.mk
  v/bsg_manycore_endpoint_fc.v
  v/bsg_manycore_endpoint_standard.v
Labels: Refactor

#479 Endpoint standard refactor / Credit limit CSR
  machines/arch_filelist.mk
  software/spmd/test_credit_limit_csr/Makefile
  software/spmd/test_credit_limit_csr/main.c
  software/spmd/test_credit_limit_csr_multi/Makefile
  software/spmd/test_credit_limit_csr_multi/main.c
  testbenches/common/v/bsg_nonsynth_manycore_io_complex.v
  testbenches/common/v/bsg_nonsynth_manycore_spmd_loader.v
  testbenches/common/v/bsg_nonsynth_manycore_testbench.v
  testbenches/dpi/bsg_nonsynth_dpi_manycore.hpp
  testbenches/dpi/bsg_nonsynth_dpi_manycore.v
  v/bsg_1hold.v
  v/bsg_manycore_endpoint.v
  v/bsg_manycore_endpoint_fc.v
  v/bsg_manycore_endpoint_standard.v
  v/bsg_manycore_hetero_socket.v
  v/bsg_manycore_hor_io_router.v
  v/bsg_manycore_link_to_cache.v
  v/bsg_manycore_lock_ctrl.v
  v/bsg_manycore_pod_ruche_array.v
  v/bsg_manycore_tile_compute_ruche.v
  v/vanilla_bean/bsg_manycore_proc_vanilla.v
  v/vanilla_bean/bsg_vanilla_pkg.v
  v/vanilla_bean/mcsr.v
  v/vanilla_bean/vanilla_core.v
Labels: DO_NOT_MERGE
